name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Ensure your branch is now 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Prevent shallow clone errors

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.email "asif.arif@gmail.com"
          git config --global user.name "asifarif"

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/muasif/PEC-AnswerHub
          git push --force https://muasif:${HF_TOKEN}@huggingface.co/spaces/muasif/PEC-AnswerHub main
